### PR TITLE
replaced deprecated google fonts plugin

### LINKED ISSUE #42: Replace deprecated plugin gatsby-plugin-prefetch-google-fonts
Gatsby throws the following error: `"gatsby-plugin-prefetch-google-fonts" threw an error while running the onPreBootstrap lifecycle:
ENOENT: no such file or directory, stat '.cache/google-fonts//fonts'`.

See: https://github.com/gatsbyjs/gatsby/issues/27607

### PR DESCRIPTION
**Pull request by LayaTaal**
Fixes #42

### CODE REVIEW

File: gatsby-config.js [hunk 1]
```diff
@@ -69,17 +69,11 @@ module.exports = {
...
-          {
-            family: "IBM Plex Mono",
-            variants: [600],
-          },
-          {
-            family: "Scope One",
-            variants: [400],
-          },
+          "IBM Plex Mono\:600",
+          "Scope One\:400",
```
Comment (tjdunklee) [inline gatsby-config.js:76]: I would be tempted to put `display: 'swap'` in here for a little faster site. If we did that, it would probably be good to do to the other self-hosted fonts we are using too.

**Review by tjdunklee — APPROVED** [review]
Thanks for fixing that! I just have one comment about a possible speed improvement. It would cause a FOUT, but that personally doesn't bother me.

File: gatsby-config.js (hunk 1 above)
Comment (LayaTaal) [reply gatsby-config.js:76]: Good call @tjdunklee , I'll update this.

**Review by bradybridges — APPROVED** [review]
This looks good to me!
